name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: poetry install
    - run: poetry run pytest